// Code generated by internal/wl/gen. DO NOT EDIT.
//
// Source files:
//   wayland.xml
//   wlr-virtual-pointer-unstable-v1.xml
//   virtual-keyboard-unstable-v1.xml
//   wlr-screencopy-unstable-v1.xml
//   wlr-foreign-toplevel-management-unstable-v1.xml
//   wlr-output-management-unstable-v1.xml
//   xdg-shell.xml
//   linux-dmabuf-v1.xml
//   viewporter.xml
//   hyprland-toplevel-export-v1.xml

package wl

// Request opcodes (index of the request in its interface's XML order).
const (
	reqHyprlandToplevelExportFrameV1Copy                                   = 0
	reqHyprlandToplevelExportFrameV1Destroy                                = 1
	reqHyprlandToplevelExportManagerV1CaptureToplevel                      = 0
	reqHyprlandToplevelExportManagerV1Destroy                              = 1
	reqHyprlandToplevelExportManagerV1CaptureToplevelWithWlrToplevelHandle = 2
	reqWlBufferDestroy                                                     = 0
	reqWlCompositorCreateSurface                                           = 0
	reqWlCompositorCreateRegion                                            = 1
	reqWlCompositorRelease                                                 = 2
	reqWlDataDeviceStartDrag                                               = 0
	reqWlDataDeviceSetSelection                                            = 1
	reqWlDataDeviceRelease                                                 = 2
	reqWlDataDeviceManagerCreateDataSource                                 = 0
	reqWlDataDeviceManagerGetDataDevice                                    = 1
	reqWlDataDeviceManagerRelease                                          = 2
	reqWlDataOfferAccept                                                   = 0
	reqWlDataOfferReceive                                                  = 1
	reqWlDataOfferDestroy                                                  = 2
	reqWlDataOfferFinish                                                   = 3
	reqWlDataOfferSetActions                                               = 4
	reqWlDataSourceOffer                                                   = 0
	reqWlDataSourceDestroy                                                 = 1
	reqWlDataSourceSetActions                                              = 2
	reqWlDisplaySync                                                       = 0
	reqWlDisplayGetRegistry                                                = 1
	reqWlFixesDestroy                                                      = 0
	reqWlFixesDestroyRegistry                                              = 1
	reqWlFixesAckGlobalRemove                                              = 2
	reqWlKeyboardRelease                                                   = 0
	reqWlOutputRelease                                                     = 0
	reqWlPointerSetCursor                                                  = 0
	reqWlPointerRelease                                                    = 1
	reqWlRegionDestroy                                                     = 0
	reqWlRegionAdd                                                         = 1
	reqWlRegionSubtract                                                    = 2
	reqWlRegistryBind                                                      = 0
	reqWlSeatGetPointer                                                    = 0
	reqWlSeatGetKeyboard                                                   = 1
	reqWlSeatGetTouch                                                      = 2
	reqWlSeatRelease                                                       = 3
	reqWlShellGetShellSurface                                              = 0
	reqWlShellSurfacePong                                                  = 0
	reqWlShellSurfaceMove                                                  = 1
	reqWlShellSurfaceResize                                                = 2
	reqWlShellSurfaceSetToplevel                                           = 3
	reqWlShellSurfaceSetTransient                                          = 4
	reqWlShellSurfaceSetFullscreen                                         = 5
	reqWlShellSurfaceSetPopup                                              = 6
	reqWlShellSurfaceSetMaximized                                          = 7
	reqWlShellSurfaceSetTitle                                              = 8
	reqWlShellSurfaceSetClass                                              = 9
	reqWlShmCreatePool                                                     = 0
	reqWlShmRelease                                                        = 1
	reqWlShmPoolCreateBuffer                                               = 0
	reqWlShmPoolDestroy                                                    = 1
	reqWlShmPoolResize                                                     = 2
	reqWlSubcompositorDestroy                                              = 0
	reqWlSubcompositorGetSubsurface                                        = 1
	reqWlSubsurfaceDestroy                                                 = 0
	reqWlSubsurfaceSetPosition                                             = 1
	reqWlSubsurfacePlaceAbove                                              = 2
	reqWlSubsurfacePlaceBelow                                              = 3
	reqWlSubsurfaceSetSync                                                 = 4
	reqWlSubsurfaceSetDesync                                               = 5
	reqWlSurfaceDestroy                                                    = 0
	reqWlSurfaceAttach                                                     = 1
	reqWlSurfaceDamage                                                     = 2
	reqWlSurfaceFrame                                                      = 3
	reqWlSurfaceSetOpaqueRegion                                            = 4
	reqWlSurfaceSetInputRegion                                             = 5
	reqWlSurfaceCommit                                                     = 6
	reqWlSurfaceSetBufferTransform                                         = 7
	reqWlSurfaceSetBufferScale                                             = 8
	reqWlSurfaceDamageBuffer                                               = 9
	reqWlSurfaceOffset                                                     = 10
	reqWlSurfaceGetRelease                                                 = 11
	reqWlTouchRelease                                                      = 0
	reqWpViewportDestroy                                                   = 0
	reqWpViewportSetSource                                                 = 1
	reqWpViewportSetDestination                                            = 2
	reqWpViewporterDestroy                                                 = 0
	reqWpViewporterGetViewport                                             = 1
	reqXdgPopupDestroy                                                     = 0
	reqXdgPopupGrab                                                        = 1
	reqXdgPopupReposition                                                  = 2
	reqXdgPositionerDestroy                                                = 0
	reqXdgPositionerSetSize                                                = 1
	reqXdgPositionerSetAnchorRect                                          = 2
	reqXdgPositionerSetAnchor                                              = 3
	reqXdgPositionerSetGravity                                             = 4
	reqXdgPositionerSetConstraintAdjustment                                = 5
	reqXdgPositionerSetOffset                                              = 6
	reqXdgPositionerSetReactive                                            = 7
	reqXdgPositionerSetParentSize                                          = 8
	reqXdgPositionerSetParentConfigure                                     = 9
	reqXdgSurfaceDestroy                                                   = 0
	reqXdgSurfaceGetToplevel                                               = 1
	reqXdgSurfaceGetPopup                                                  = 2
	reqXdgSurfaceSetWindowGeometry                                         = 3
	reqXdgSurfaceAckConfigure                                              = 4
	reqXdgToplevelDestroy                                                  = 0
	reqXdgToplevelSetParent                                                = 1
	reqXdgToplevelSetTitle                                                 = 2
	reqXdgToplevelSetAppId                                                 = 3
	reqXdgToplevelShowWindowMenu                                           = 4
	reqXdgToplevelMove                                                     = 5
	reqXdgToplevelResize                                                   = 6
	reqXdgToplevelSetMaxSize                                               = 7
	reqXdgToplevelSetMinSize                                               = 8
	reqXdgToplevelSetMaximized                                             = 9
	reqXdgToplevelUnsetMaximized                                           = 10
	reqXdgToplevelSetFullscreen                                            = 11
	reqXdgToplevelUnsetFullscreen                                          = 12
	reqXdgToplevelSetMinimized                                             = 13
	reqXdgWmBaseDestroy                                                    = 0
	reqXdgWmBaseCreatePositioner                                           = 1
	reqXdgWmBaseGetXdgSurface                                              = 2
	reqXdgWmBasePong                                                       = 3
	reqZwlrForeignToplevelHandleV1SetMaximized                             = 0
	reqZwlrForeignToplevelHandleV1UnsetMaximized                           = 1
	reqZwlrForeignToplevelHandleV1SetMinimized                             = 2
	reqZwlrForeignToplevelHandleV1UnsetMinimized                           = 3
	reqZwlrForeignToplevelHandleV1Activate                                 = 4
	reqZwlrForeignToplevelHandleV1Close                                    = 5
	reqZwlrForeignToplevelHandleV1SetRectangle                             = 6
	reqZwlrForeignToplevelHandleV1Destroy                                  = 7
	reqZwlrForeignToplevelHandleV1SetFullscreen                            = 8
	reqZwlrForeignToplevelHandleV1UnsetFullscreen                          = 9
	reqZwlrForeignToplevelManagerV1Stop                                    = 0
	reqZwlrOutputConfigurationHeadV1SetMode                                = 0
	reqZwlrOutputConfigurationHeadV1SetCustomMode                          = 1
	reqZwlrOutputConfigurationHeadV1SetPosition                            = 2
	reqZwlrOutputConfigurationHeadV1SetTransform                           = 3
	reqZwlrOutputConfigurationHeadV1SetScale                               = 4
	reqZwlrOutputConfigurationHeadV1SetAdaptiveSync                        = 5
	reqZwlrOutputConfigurationV1EnableHead                                 = 0
	reqZwlrOutputConfigurationV1DisableHead                                = 1
	reqZwlrOutputConfigurationV1Apply                                      = 2
	reqZwlrOutputConfigurationV1Test                                       = 3
	reqZwlrOutputConfigurationV1Destroy                                    = 4
	reqZwlrOutputHeadV1Release                                             = 0
	reqZwlrOutputManagerV1CreateConfiguration                              = 0
	reqZwlrOutputManagerV1Stop                                             = 1
	reqZwlrOutputModeV1Release                                             = 0
	reqZwlrScreencopyFrameV1Copy                                           = 0
	reqZwlrScreencopyFrameV1Destroy                                        = 1
	reqZwlrScreencopyFrameV1CopyWithDamage                                 = 2
	reqZwlrScreencopyManagerV1CaptureOutput                                = 0
	reqZwlrScreencopyManagerV1CaptureOutputRegion                          = 1
	reqZwlrScreencopyManagerV1Destroy                                      = 2
	reqZwlrVirtualPointerManagerV1CreateVirtualPointer                     = 0
	reqZwlrVirtualPointerManagerV1Destroy                                  = 1
	reqZwlrVirtualPointerManagerV1CreateVirtualPointerWithOutput           = 2
	reqZwlrVirtualPointerV1Motion                                          = 0
	reqZwlrVirtualPointerV1MotionAbsolute                                  = 1
	reqZwlrVirtualPointerV1Button                                          = 2
	reqZwlrVirtualPointerV1Axis                                            = 3
	reqZwlrVirtualPointerV1Frame                                           = 4
	reqZwlrVirtualPointerV1AxisSource                                      = 5
	reqZwlrVirtualPointerV1AxisStop                                        = 6
	reqZwlrVirtualPointerV1AxisDiscrete                                    = 7
	reqZwlrVirtualPointerV1Destroy                                         = 8
	reqZwpLinuxBufferParamsV1Destroy                                       = 0
	reqZwpLinuxBufferParamsV1Add                                           = 1
	reqZwpLinuxBufferParamsV1Create                                        = 2
	reqZwpLinuxBufferParamsV1CreateImmed                                   = 3
	reqZwpLinuxBufferParamsV1SetSamplingDevice                             = 4
	reqZwpLinuxDmabufFeedbackV1Destroy                                     = 0
	reqZwpLinuxDmabufV1Destroy                                             = 0
	reqZwpLinuxDmabufV1CreateParams                                        = 1
	reqZwpLinuxDmabufV1GetDefaultFeedback                                  = 2
	reqZwpLinuxDmabufV1GetSurfaceFeedback                                  = 3
	reqZwpVirtualKeyboardManagerV1CreateVirtualKeyboard                    = 0
	reqZwpVirtualKeyboardV1Keymap                                          = 0
	reqZwpVirtualKeyboardV1Key                                             = 1
	reqZwpVirtualKeyboardV1Modifiers                                       = 2
	reqZwpVirtualKeyboardV1Destroy                                         = 3
)

// Event opcodes (index of the event in its interface's XML order).
const (
	evtHyprlandToplevelExportFrameV1Buffer         = 0
	evtHyprlandToplevelExportFrameV1Damage         = 1
	evtHyprlandToplevelExportFrameV1Flags          = 2
	evtHyprlandToplevelExportFrameV1Ready          = 3
	evtHyprlandToplevelExportFrameV1Failed         = 4
	evtHyprlandToplevelExportFrameV1LinuxDmabuf    = 5
	evtHyprlandToplevelExportFrameV1BufferDone     = 6
	evtWlBufferRelease                             = 0
	evtWlCallbackDone                              = 0
	evtWlDataDeviceDataOffer                       = 0
	evtWlDataDeviceEnter                           = 1
	evtWlDataDeviceLeave                           = 2
	evtWlDataDeviceMotion                          = 3
	evtWlDataDeviceDrop                            = 4
	evtWlDataDeviceSelection                       = 5
	evtWlDataOfferOffer                            = 0
	evtWlDataOfferSourceActions                    = 1
	evtWlDataOfferAction                           = 2
	evtWlDataSourceTarget                          = 0
	evtWlDataSourceSend                            = 1
	evtWlDataSourceCancelled                       = 2
	evtWlDataSourceDndDropPerformed                = 3
	evtWlDataSourceDndFinished                     = 4
	evtWlDataSourceAction                          = 5
	evtWlDisplayError                              = 0
	evtWlDisplayDeleteId                           = 1
	evtWlKeyboardKeymap                            = 0
	evtWlKeyboardEnter                             = 1
	evtWlKeyboardLeave                             = 2
	evtWlKeyboardKey                               = 3
	evtWlKeyboardModifiers                         = 4
	evtWlKeyboardRepeatInfo                        = 5
	evtWlOutputGeometry                            = 0
	evtWlOutputMode                                = 1
	evtWlOutputDone                                = 2
	evtWlOutputScale                               = 3
	evtWlOutputName                                = 4
	evtWlOutputDescription                         = 5
	evtWlPointerEnter                              = 0
	evtWlPointerLeave                              = 1
	evtWlPointerMotion                             = 2
	evtWlPointerButton                             = 3
	evtWlPointerAxis                               = 4
	evtWlPointerFrame                              = 5
	evtWlPointerAxisSource                         = 6
	evtWlPointerAxisStop                           = 7
	evtWlPointerAxisDiscrete                       = 8
	evtWlPointerAxisValue120                       = 9
	evtWlPointerAxisRelativeDirection              = 10
	evtWlPointerWarp                               = 11
	evtWlRegistryGlobal                            = 0
	evtWlRegistryGlobalRemove                      = 1
	evtWlSeatCapabilities                          = 0
	evtWlSeatName                                  = 1
	evtWlShellSurfacePing                          = 0
	evtWlShellSurfaceConfigure                     = 1
	evtWlShellSurfacePopupDone                     = 2
	evtWlShmFormat                                 = 0
	evtWlSurfaceEnter                              = 0
	evtWlSurfaceLeave                              = 1
	evtWlSurfacePreferredBufferScale               = 2
	evtWlSurfacePreferredBufferTransform           = 3
	evtWlTouchDown                                 = 0
	evtWlTouchUp                                   = 1
	evtWlTouchMotion                               = 2
	evtWlTouchFrame                                = 3
	evtWlTouchCancel                               = 4
	evtWlTouchShape                                = 5
	evtWlTouchOrientation                          = 6
	evtXdgPopupConfigure                           = 0
	evtXdgPopupPopupDone                           = 1
	evtXdgPopupRepositioned                        = 2
	evtXdgSurfaceConfigure                         = 0
	evtXdgToplevelConfigure                        = 0
	evtXdgToplevelClose                            = 1
	evtXdgToplevelConfigureBounds                  = 2
	evtXdgToplevelWmCapabilities                   = 3
	evtXdgWmBasePing                               = 0
	evtZwlrForeignToplevelHandleV1Title            = 0
	evtZwlrForeignToplevelHandleV1AppId            = 1
	evtZwlrForeignToplevelHandleV1OutputEnter      = 2
	evtZwlrForeignToplevelHandleV1OutputLeave      = 3
	evtZwlrForeignToplevelHandleV1State            = 4
	evtZwlrForeignToplevelHandleV1Done             = 5
	evtZwlrForeignToplevelHandleV1Closed           = 6
	evtZwlrForeignToplevelHandleV1Parent           = 7
	evtZwlrForeignToplevelManagerV1Toplevel        = 0
	evtZwlrForeignToplevelManagerV1Finished        = 1
	evtZwlrOutputConfigurationV1Succeeded          = 0
	evtZwlrOutputConfigurationV1Failed             = 1
	evtZwlrOutputConfigurationV1Cancelled          = 2
	evtZwlrOutputHeadV1Name                        = 0
	evtZwlrOutputHeadV1Description                 = 1
	evtZwlrOutputHeadV1PhysicalSize                = 2
	evtZwlrOutputHeadV1Mode                        = 3
	evtZwlrOutputHeadV1Enabled                     = 4
	evtZwlrOutputHeadV1CurrentMode                 = 5
	evtZwlrOutputHeadV1Position                    = 6
	evtZwlrOutputHeadV1Transform                   = 7
	evtZwlrOutputHeadV1Scale                       = 8
	evtZwlrOutputHeadV1Finished                    = 9
	evtZwlrOutputHeadV1Make                        = 10
	evtZwlrOutputHeadV1Model                       = 11
	evtZwlrOutputHeadV1SerialNumber                = 12
	evtZwlrOutputHeadV1AdaptiveSync                = 13
	evtZwlrOutputManagerV1Head                     = 0
	evtZwlrOutputManagerV1Done                     = 1
	evtZwlrOutputManagerV1Finished                 = 2
	evtZwlrOutputModeV1Size                        = 0
	evtZwlrOutputModeV1Refresh                     = 1
	evtZwlrOutputModeV1Preferred                   = 2
	evtZwlrOutputModeV1Finished                    = 3
	evtZwlrScreencopyFrameV1Buffer                 = 0
	evtZwlrScreencopyFrameV1Flags                  = 1
	evtZwlrScreencopyFrameV1Ready                  = 2
	evtZwlrScreencopyFrameV1Failed                 = 3
	evtZwlrScreencopyFrameV1Damage                 = 4
	evtZwlrScreencopyFrameV1LinuxDmabuf            = 5
	evtZwlrScreencopyFrameV1BufferDone             = 6
	evtZwpLinuxBufferParamsV1Created               = 0
	evtZwpLinuxBufferParamsV1Failed                = 1
	evtZwpLinuxDmabufFeedbackV1Done                = 0
	evtZwpLinuxDmabufFeedbackV1FormatTable         = 1
	evtZwpLinuxDmabufFeedbackV1MainDevice          = 2
	evtZwpLinuxDmabufFeedbackV1TrancheDone         = 3
	evtZwpLinuxDmabufFeedbackV1TrancheTargetDevice = 4
	evtZwpLinuxDmabufFeedbackV1TrancheFormats      = 5
	evtZwpLinuxDmabufFeedbackV1TrancheFlags        = 6
	evtZwpLinuxDmabufV1Format                      = 0
	evtZwpLinuxDmabufV1Modifier                    = 1
)

// Interface names.
const (
	ifaceHyprlandToplevelExportFrameV1   = "hyprland_toplevel_export_frame_v1"
	ifaceHyprlandToplevelExportManagerV1 = "hyprland_toplevel_export_manager_v1"
	ifaceWlBuffer                        = "wl_buffer"
	ifaceWlCallback                      = "wl_callback"
	ifaceWlCompositor                    = "wl_compositor"
	ifaceWlDataDevice                    = "wl_data_device"
	ifaceWlDataDeviceManager             = "wl_data_device_manager"
	ifaceWlDataOffer                     = "wl_data_offer"
	ifaceWlDataSource                    = "wl_data_source"
	ifaceWlDisplay                       = "wl_display"
	ifaceWlFixes                         = "wl_fixes"
	ifaceWlKeyboard                      = "wl_keyboard"
	ifaceWlOutput                        = "wl_output"
	ifaceWlPointer                       = "wl_pointer"
	ifaceWlRegion                        = "wl_region"
	ifaceWlRegistry                      = "wl_registry"
	ifaceWlSeat                          = "wl_seat"
	ifaceWlShell                         = "wl_shell"
	ifaceWlShellSurface                  = "wl_shell_surface"
	ifaceWlShm                           = "wl_shm"
	ifaceWlShmPool                       = "wl_shm_pool"
	ifaceWlSubcompositor                 = "wl_subcompositor"
	ifaceWlSubsurface                    = "wl_subsurface"
	ifaceWlSurface                       = "wl_surface"
	ifaceWlTouch                         = "wl_touch"
	ifaceWpViewport                      = "wp_viewport"
	ifaceWpViewporter                    = "wp_viewporter"
	ifaceXdgPopup                        = "xdg_popup"
	ifaceXdgPositioner                   = "xdg_positioner"
	ifaceXdgSurface                      = "xdg_surface"
	ifaceXdgToplevel                     = "xdg_toplevel"
	ifaceXdgWmBase                       = "xdg_wm_base"
	ifaceZwlrForeignToplevelHandleV1     = "zwlr_foreign_toplevel_handle_v1"
	ifaceZwlrForeignToplevelManagerV1    = "zwlr_foreign_toplevel_manager_v1"
	ifaceZwlrOutputConfigurationHeadV1   = "zwlr_output_configuration_head_v1"
	ifaceZwlrOutputConfigurationV1       = "zwlr_output_configuration_v1"
	ifaceZwlrOutputHeadV1                = "zwlr_output_head_v1"
	ifaceZwlrOutputManagerV1             = "zwlr_output_manager_v1"
	ifaceZwlrOutputModeV1                = "zwlr_output_mode_v1"
	ifaceZwlrScreencopyFrameV1           = "zwlr_screencopy_frame_v1"
	ifaceZwlrScreencopyManagerV1         = "zwlr_screencopy_manager_v1"
	ifaceZwlrVirtualPointerManagerV1     = "zwlr_virtual_pointer_manager_v1"
	ifaceZwlrVirtualPointerV1            = "zwlr_virtual_pointer_v1"
	ifaceZwpLinuxBufferParamsV1          = "zwp_linux_buffer_params_v1"
	ifaceZwpLinuxDmabufFeedbackV1        = "zwp_linux_dmabuf_feedback_v1"
	ifaceZwpLinuxDmabufV1                = "zwp_linux_dmabuf_v1"
	ifaceZwpVirtualKeyboardManagerV1     = "zwp_virtual_keyboard_manager_v1"
	ifaceZwpVirtualKeyboardV1            = "zwp_virtual_keyboard_v1"
)

// protoIfaces describes every interface of the bundled protocols: its
// maximum version and, for each request and event, its opcode (the slice
// index) and argument signature.
var protoIfaces = map[string]*ifaceSpec{
	"hyprland_toplevel_export_frame_v1": {
		Name:    "hyprland_toplevel_export_frame_v1",
		Version: 2,
		Requests: []msgSpec{
			{Name: "copy", Opcode: 0, Since: 1, Args: []argSpec{{Name: "buffer", Type: argObject, Interface: "wl_buffer"}, {Name: "ignore_damage", Type: argInt}}},
			{Name: "destroy", Opcode: 1, Since: 1, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "buffer", Opcode: 0, Since: 1, Args: []argSpec{{Name: "format", Type: argUint}, {Name: "width", Type: argUint}, {Name: "height", Type: argUint}, {Name: "stride", Type: argUint}}},
			{Name: "damage", Opcode: 1, Since: 1, Args: []argSpec{{Name: "x", Type: argUint}, {Name: "y", Type: argUint}, {Name: "width", Type: argUint}, {Name: "height", Type: argUint}}},
			{Name: "flags", Opcode: 2, Since: 1, Args: []argSpec{{Name: "flags", Type: argUint}}},
			{Name: "ready", Opcode: 3, Since: 1, Args: []argSpec{{Name: "tv_sec_hi", Type: argUint}, {Name: "tv_sec_lo", Type: argUint}, {Name: "tv_nsec", Type: argUint}}},
			{Name: "failed", Opcode: 4, Since: 1},
			{Name: "linux_dmabuf", Opcode: 5, Since: 1, Args: []argSpec{{Name: "format", Type: argUint}, {Name: "width", Type: argUint}, {Name: "height", Type: argUint}}},
			{Name: "buffer_done", Opcode: 6, Since: 1},
		},
	},
	"hyprland_toplevel_export_manager_v1": {
		Name:    "hyprland_toplevel_export_manager_v1",
		Version: 2,
		Requests: []msgSpec{
			{Name: "capture_toplevel", Opcode: 0, Since: 1, Args: []argSpec{{Name: "frame", Type: argNewID, Interface: "hyprland_toplevel_export_frame_v1"}, {Name: "overlay_cursor", Type: argInt}, {Name: "handle", Type: argUint}}},
			{Name: "destroy", Opcode: 1, Since: 1, Destructor: true},
			{Name: "capture_toplevel_with_wlr_toplevel_handle", Opcode: 2, Since: 2, Args: []argSpec{{Name: "frame", Type: argNewID, Interface: "hyprland_toplevel_export_frame_v1"}, {Name: "overlay_cursor", Type: argInt}, {Name: "handle", Type: argObject, Interface: "zwlr_foreign_toplevel_handle_v1"}}},
		},
	},
	"wl_buffer": {
		Name:    "wl_buffer",
		Version: 1,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "release", Opcode: 0, Since: 1},
		},
	},
	"wl_callback": {
		Name:    "wl_callback",
		Version: 1,
		Events: []msgSpec{
			{Name: "done", Opcode: 0, Since: 1, Destructor: true, Args: []argSpec{{Name: "callback_data", Type: argUint}}},
		},
	},
	"wl_compositor": {
		Name:    "wl_compositor",
		Version: 7,
		Requests: []msgSpec{
			{Name: "create_surface", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_surface"}}},
			{Name: "create_region", Opcode: 1, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_region"}}},
			{Name: "release", Opcode: 2, Since: 7, Destructor: true},
		},
	},
	"wl_data_device": {
		Name:    "wl_data_device",
		Version: 4,
		Requests: []msgSpec{
			{Name: "start_drag", Opcode: 0, Since: 1, Args: []argSpec{{Name: "source", Type: argObject, Interface: "wl_data_source", Nullable: true}, {Name: "origin", Type: argObject, Interface: "wl_surface"}, {Name: "icon", Type: argObject, Interface: "wl_surface", Nullable: true}, {Name: "serial", Type: argUint}}},
			{Name: "set_selection", Opcode: 1, Since: 1, Args: []argSpec{{Name: "source", Type: argObject, Interface: "wl_data_source", Nullable: true}, {Name: "serial", Type: argUint}}},
			{Name: "release", Opcode: 2, Since: 2, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "data_offer", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_data_offer"}}},
			{Name: "enter", Opcode: 1, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "surface", Type: argObject, Interface: "wl_surface"}, {Name: "x", Type: argFixed}, {Name: "y", Type: argFixed}, {Name: "id", Type: argObject, Interface: "wl_data_offer", Nullable: true}}},
			{Name: "leave", Opcode: 2, Since: 1},
			{Name: "motion", Opcode: 3, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "x", Type: argFixed}, {Name: "y", Type: argFixed}}},
			{Name: "drop", Opcode: 4, Since: 1},
			{Name: "selection", Opcode: 5, Since: 1, Args: []argSpec{{Name: "id", Type: argObject, Interface: "wl_data_offer", Nullable: true}}},
		},
	},
	"wl_data_device_manager": {
		Name:    "wl_data_device_manager",
		Version: 4,
		Requests: []msgSpec{
			{Name: "create_data_source", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_data_source"}}},
			{Name: "get_data_device", Opcode: 1, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_data_device"}, {Name: "seat", Type: argObject, Interface: "wl_seat"}}},
			{Name: "release", Opcode: 2, Since: 4, Destructor: true},
		},
	},
	"wl_data_offer": {
		Name:    "wl_data_offer",
		Version: 4,
		Requests: []msgSpec{
			{Name: "accept", Opcode: 0, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "mime_type", Type: argString, Nullable: true}}},
			{Name: "receive", Opcode: 1, Since: 1, Args: []argSpec{{Name: "mime_type", Type: argString}, {Name: "fd", Type: argFD}}},
			{Name: "destroy", Opcode: 2, Since: 1, Destructor: true},
			{Name: "finish", Opcode: 3, Since: 3},
			{Name: "set_actions", Opcode: 4, Since: 3, Args: []argSpec{{Name: "dnd_actions", Type: argUint}, {Name: "preferred_action", Type: argUint}}},
		},
		Events: []msgSpec{
			{Name: "offer", Opcode: 0, Since: 1, Args: []argSpec{{Name: "mime_type", Type: argString}}},
			{Name: "source_actions", Opcode: 1, Since: 3, Args: []argSpec{{Name: "source_actions", Type: argUint}}},
			{Name: "action", Opcode: 2, Since: 3, Args: []argSpec{{Name: "dnd_action", Type: argUint}}},
		},
	},
	"wl_data_source": {
		Name:    "wl_data_source",
		Version: 4,
		Requests: []msgSpec{
			{Name: "offer", Opcode: 0, Since: 1, Args: []argSpec{{Name: "mime_type", Type: argString}}},
			{Name: "destroy", Opcode: 1, Since: 1, Destructor: true},
			{Name: "set_actions", Opcode: 2, Since: 3, Args: []argSpec{{Name: "dnd_actions", Type: argUint}}},
		},
		Events: []msgSpec{
			{Name: "target", Opcode: 0, Since: 1, Args: []argSpec{{Name: "mime_type", Type: argString, Nullable: true}}},
			{Name: "send", Opcode: 1, Since: 1, Args: []argSpec{{Name: "mime_type", Type: argString}, {Name: "fd", Type: argFD}}},
			{Name: "cancelled", Opcode: 2, Since: 1},
			{Name: "dnd_drop_performed", Opcode: 3, Since: 3},
			{Name: "dnd_finished", Opcode: 4, Since: 3},
			{Name: "action", Opcode: 5, Since: 3, Args: []argSpec{{Name: "dnd_action", Type: argUint}}},
		},
	},
	"wl_display": {
		Name:    "wl_display",
		Version: 1,
		Requests: []msgSpec{
			{Name: "sync", Opcode: 0, Since: 1, Args: []argSpec{{Name: "callback", Type: argNewID, Interface: "wl_callback"}}},
			{Name: "get_registry", Opcode: 1, Since: 1, Args: []argSpec{{Name: "registry", Type: argNewID, Interface: "wl_registry"}}},
		},
		Events: []msgSpec{
			{Name: "error", Opcode: 0, Since: 1, Args: []argSpec{{Name: "object_id", Type: argObject}, {Name: "code", Type: argUint}, {Name: "message", Type: argString}}},
			{Name: "delete_id", Opcode: 1, Since: 1, Args: []argSpec{{Name: "id", Type: argUint}}},
		},
	},
	"wl_fixes": {
		Name:    "wl_fixes",
		Version: 2,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "destroy_registry", Opcode: 1, Since: 1, Args: []argSpec{{Name: "registry", Type: argObject, Interface: "wl_registry"}}},
			{Name: "ack_global_remove", Opcode: 2, Since: 2, Args: []argSpec{{Name: "registry", Type: argObject, Interface: "wl_registry"}, {Name: "name", Type: argUint}}},
		},
	},
	"wl_keyboard": {
		Name:    "wl_keyboard",
		Version: 11,
		Requests: []msgSpec{
			{Name: "release", Opcode: 0, Since: 3, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "keymap", Opcode: 0, Since: 1, Args: []argSpec{{Name: "format", Type: argUint}, {Name: "fd", Type: argFD}, {Name: "size", Type: argUint}}},
			{Name: "enter", Opcode: 1, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "surface", Type: argObject, Interface: "wl_surface"}, {Name: "keys", Type: argArray}}},
			{Name: "leave", Opcode: 2, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "surface", Type: argObject, Interface: "wl_surface"}}},
			{Name: "key", Opcode: 3, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "time", Type: argUint}, {Name: "key", Type: argUint}, {Name: "state", Type: argUint}}},
			{Name: "modifiers", Opcode: 4, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "mods_depressed", Type: argUint}, {Name: "mods_latched", Type: argUint}, {Name: "mods_locked", Type: argUint}, {Name: "group", Type: argUint}}},
			{Name: "repeat_info", Opcode: 5, Since: 4, Args: []argSpec{{Name: "rate", Type: argInt}, {Name: "delay", Type: argInt}}},
		},
	},
	"wl_output": {
		Name:    "wl_output",
		Version: 4,
		Requests: []msgSpec{
			{Name: "release", Opcode: 0, Since: 3, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "geometry", Opcode: 0, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "physical_width", Type: argInt}, {Name: "physical_height", Type: argInt}, {Name: "subpixel", Type: argInt}, {Name: "make", Type: argString}, {Name: "model", Type: argString}, {Name: "transform", Type: argInt}}},
			{Name: "mode", Opcode: 1, Since: 1, Args: []argSpec{{Name: "flags", Type: argUint}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}, {Name: "refresh", Type: argInt}}},
			{Name: "done", Opcode: 2, Since: 2},
			{Name: "scale", Opcode: 3, Since: 2, Args: []argSpec{{Name: "factor", Type: argInt}}},
			{Name: "name", Opcode: 4, Since: 4, Args: []argSpec{{Name: "name", Type: argString}}},
			{Name: "description", Opcode: 5, Since: 4, Args: []argSpec{{Name: "description", Type: argString}}},
		},
	},
	"wl_pointer": {
		Name:    "wl_pointer",
		Version: 11,
		Requests: []msgSpec{
			{Name: "set_cursor", Opcode: 0, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "surface", Type: argObject, Interface: "wl_surface", Nullable: true}, {Name: "hotspot_x", Type: argInt}, {Name: "hotspot_y", Type: argInt}}},
			{Name: "release", Opcode: 1, Since: 3, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "enter", Opcode: 0, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "surface", Type: argObject, Interface: "wl_surface"}, {Name: "surface_x", Type: argFixed}, {Name: "surface_y", Type: argFixed}}},
			{Name: "leave", Opcode: 1, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "surface", Type: argObject, Interface: "wl_surface"}}},
			{Name: "motion", Opcode: 2, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "surface_x", Type: argFixed}, {Name: "surface_y", Type: argFixed}}},
			{Name: "button", Opcode: 3, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "time", Type: argUint}, {Name: "button", Type: argUint}, {Name: "state", Type: argUint}}},
			{Name: "axis", Opcode: 4, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "axis", Type: argUint}, {Name: "value", Type: argFixed}}},
			{Name: "frame", Opcode: 5, Since: 5},
			{Name: "axis_source", Opcode: 6, Since: 5, Args: []argSpec{{Name: "axis_source", Type: argUint}}},
			{Name: "axis_stop", Opcode: 7, Since: 5, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "axis", Type: argUint}}},
			{Name: "axis_discrete", Opcode: 8, Since: 5, Args: []argSpec{{Name: "axis", Type: argUint}, {Name: "discrete", Type: argInt}}},
			{Name: "axis_value120", Opcode: 9, Since: 8, Args: []argSpec{{Name: "axis", Type: argUint}, {Name: "value120", Type: argInt}}},
			{Name: "axis_relative_direction", Opcode: 10, Since: 9, Args: []argSpec{{Name: "axis", Type: argUint}, {Name: "direction", Type: argUint}}},
			{Name: "warp", Opcode: 11, Since: 11, Args: []argSpec{{Name: "surface_x", Type: argFixed}, {Name: "surface_y", Type: argFixed}}},
		},
	},
	"wl_region": {
		Name:    "wl_region",
		Version: 7,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "add", Opcode: 1, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "subtract", Opcode: 2, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
		},
	},
	"wl_registry": {
		Name:    "wl_registry",
		Version: 1,
		Requests: []msgSpec{
			{Name: "bind", Opcode: 0, Since: 1, Args: []argSpec{{Name: "name", Type: argUint}, {Name: "id", Type: argNewID}}},
		},
		Events: []msgSpec{
			{Name: "global", Opcode: 0, Since: 1, Args: []argSpec{{Name: "name", Type: argUint}, {Name: "interface", Type: argString}, {Name: "version", Type: argUint}}},
			{Name: "global_remove", Opcode: 1, Since: 1, Args: []argSpec{{Name: "name", Type: argUint}}},
		},
	},
	"wl_seat": {
		Name:    "wl_seat",
		Version: 11,
		Requests: []msgSpec{
			{Name: "get_pointer", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_pointer"}}},
			{Name: "get_keyboard", Opcode: 1, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_keyboard"}}},
			{Name: "get_touch", Opcode: 2, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_touch"}}},
			{Name: "release", Opcode: 3, Since: 5, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "capabilities", Opcode: 0, Since: 1, Args: []argSpec{{Name: "capabilities", Type: argUint}}},
			{Name: "name", Opcode: 1, Since: 2, Args: []argSpec{{Name: "name", Type: argString}}},
		},
	},
	"wl_shell": {
		Name:    "wl_shell",
		Version: 1,
		Requests: []msgSpec{
			{Name: "get_shell_surface", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_shell_surface"}, {Name: "surface", Type: argObject, Interface: "wl_surface"}}},
		},
	},
	"wl_shell_surface": {
		Name:    "wl_shell_surface",
		Version: 1,
		Requests: []msgSpec{
			{Name: "pong", Opcode: 0, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}}},
			{Name: "move", Opcode: 1, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}, {Name: "serial", Type: argUint}}},
			{Name: "resize", Opcode: 2, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}, {Name: "serial", Type: argUint}, {Name: "edges", Type: argUint}}},
			{Name: "set_toplevel", Opcode: 3, Since: 1},
			{Name: "set_transient", Opcode: 4, Since: 1, Args: []argSpec{{Name: "parent", Type: argObject, Interface: "wl_surface"}, {Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "flags", Type: argUint}}},
			{Name: "set_fullscreen", Opcode: 5, Since: 1, Args: []argSpec{{Name: "method", Type: argUint}, {Name: "framerate", Type: argUint}, {Name: "output", Type: argObject, Interface: "wl_output", Nullable: true}}},
			{Name: "set_popup", Opcode: 6, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}, {Name: "serial", Type: argUint}, {Name: "parent", Type: argObject, Interface: "wl_surface"}, {Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "flags", Type: argUint}}},
			{Name: "set_maximized", Opcode: 7, Since: 1, Args: []argSpec{{Name: "output", Type: argObject, Interface: "wl_output", Nullable: true}}},
			{Name: "set_title", Opcode: 8, Since: 1, Args: []argSpec{{Name: "title", Type: argString}}},
			{Name: "set_class", Opcode: 9, Since: 1, Args: []argSpec{{Name: "class_", Type: argString}}},
		},
		Events: []msgSpec{
			{Name: "ping", Opcode: 0, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}}},
			{Name: "configure", Opcode: 1, Since: 1, Args: []argSpec{{Name: "edges", Type: argUint}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "popup_done", Opcode: 2, Since: 1},
		},
	},
	"wl_shm": {
		Name:    "wl_shm",
		Version: 3,
		Requests: []msgSpec{
			{Name: "create_pool", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_shm_pool"}, {Name: "fd", Type: argFD}, {Name: "size", Type: argInt}}},
			{Name: "release", Opcode: 1, Since: 2, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "format", Opcode: 0, Since: 1, Args: []argSpec{{Name: "format", Type: argUint}}},
		},
	},
	"wl_shm_pool": {
		Name:    "wl_shm_pool",
		Version: 3,
		Requests: []msgSpec{
			{Name: "create_buffer", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_buffer"}, {Name: "offset", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}, {Name: "stride", Type: argInt}, {Name: "format", Type: argUint}}},
			{Name: "destroy", Opcode: 1, Since: 1, Destructor: true},
			{Name: "resize", Opcode: 2, Since: 1, Args: []argSpec{{Name: "size", Type: argInt}}},
		},
	},
	"wl_subcompositor": {
		Name:    "wl_subcompositor",
		Version: 1,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "get_subsurface", Opcode: 1, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wl_subsurface"}, {Name: "surface", Type: argObject, Interface: "wl_surface"}, {Name: "parent", Type: argObject, Interface: "wl_surface"}}},
		},
	},
	"wl_subsurface": {
		Name:    "wl_subsurface",
		Version: 1,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "set_position", Opcode: 1, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}}},
			{Name: "place_above", Opcode: 2, Since: 1, Args: []argSpec{{Name: "sibling", Type: argObject, Interface: "wl_surface"}}},
			{Name: "place_below", Opcode: 3, Since: 1, Args: []argSpec{{Name: "sibling", Type: argObject, Interface: "wl_surface"}}},
			{Name: "set_sync", Opcode: 4, Since: 1},
			{Name: "set_desync", Opcode: 5, Since: 1},
		},
	},
	"wl_surface": {
		Name:    "wl_surface",
		Version: 7,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "attach", Opcode: 1, Since: 1, Args: []argSpec{{Name: "buffer", Type: argObject, Interface: "wl_buffer", Nullable: true}, {Name: "x", Type: argInt}, {Name: "y", Type: argInt}}},
			{Name: "damage", Opcode: 2, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "frame", Opcode: 3, Since: 1, Args: []argSpec{{Name: "callback", Type: argNewID, Interface: "wl_callback"}}},
			{Name: "set_opaque_region", Opcode: 4, Since: 1, Args: []argSpec{{Name: "region", Type: argObject, Interface: "wl_region", Nullable: true}}},
			{Name: "set_input_region", Opcode: 5, Since: 1, Args: []argSpec{{Name: "region", Type: argObject, Interface: "wl_region", Nullable: true}}},
			{Name: "commit", Opcode: 6, Since: 1},
			{Name: "set_buffer_transform", Opcode: 7, Since: 2, Args: []argSpec{{Name: "transform", Type: argInt}}},
			{Name: "set_buffer_scale", Opcode: 8, Since: 3, Args: []argSpec{{Name: "scale", Type: argInt}}},
			{Name: "damage_buffer", Opcode: 9, Since: 4, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "offset", Opcode: 10, Since: 5, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}}},
			{Name: "get_release", Opcode: 11, Since: 7, Args: []argSpec{{Name: "callback", Type: argNewID, Interface: "wl_callback"}}},
		},
		Events: []msgSpec{
			{Name: "enter", Opcode: 0, Since: 1, Args: []argSpec{{Name: "output", Type: argObject, Interface: "wl_output"}}},
			{Name: "leave", Opcode: 1, Since: 1, Args: []argSpec{{Name: "output", Type: argObject, Interface: "wl_output"}}},
			{Name: "preferred_buffer_scale", Opcode: 2, Since: 6, Args: []argSpec{{Name: "factor", Type: argInt}}},
			{Name: "preferred_buffer_transform", Opcode: 3, Since: 6, Args: []argSpec{{Name: "transform", Type: argUint}}},
		},
	},
	"wl_touch": {
		Name:    "wl_touch",
		Version: 11,
		Requests: []msgSpec{
			{Name: "release", Opcode: 0, Since: 3, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "down", Opcode: 0, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "time", Type: argUint}, {Name: "surface", Type: argObject, Interface: "wl_surface"}, {Name: "id", Type: argInt}, {Name: "x", Type: argFixed}, {Name: "y", Type: argFixed}}},
			{Name: "up", Opcode: 1, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}, {Name: "time", Type: argUint}, {Name: "id", Type: argInt}}},
			{Name: "motion", Opcode: 2, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "id", Type: argInt}, {Name: "x", Type: argFixed}, {Name: "y", Type: argFixed}}},
			{Name: "frame", Opcode: 3, Since: 1},
			{Name: "cancel", Opcode: 4, Since: 1},
			{Name: "shape", Opcode: 5, Since: 6, Args: []argSpec{{Name: "id", Type: argInt}, {Name: "major", Type: argFixed}, {Name: "minor", Type: argFixed}}},
			{Name: "orientation", Opcode: 6, Since: 6, Args: []argSpec{{Name: "id", Type: argInt}, {Name: "orientation", Type: argFixed}}},
		},
	},
	"wp_viewport": {
		Name:    "wp_viewport",
		Version: 1,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "set_source", Opcode: 1, Since: 1, Args: []argSpec{{Name: "x", Type: argFixed}, {Name: "y", Type: argFixed}, {Name: "width", Type: argFixed}, {Name: "height", Type: argFixed}}},
			{Name: "set_destination", Opcode: 2, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
		},
	},
	"wp_viewporter": {
		Name:    "wp_viewporter",
		Version: 1,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "get_viewport", Opcode: 1, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "wp_viewport"}, {Name: "surface", Type: argObject, Interface: "wl_surface"}}},
		},
	},
	"xdg_popup": {
		Name:    "xdg_popup",
		Version: 7,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "grab", Opcode: 1, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}, {Name: "serial", Type: argUint}}},
			{Name: "reposition", Opcode: 2, Since: 3, Args: []argSpec{{Name: "positioner", Type: argObject, Interface: "xdg_positioner"}, {Name: "token", Type: argUint}}},
		},
		Events: []msgSpec{
			{Name: "configure", Opcode: 0, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "popup_done", Opcode: 1, Since: 1},
			{Name: "repositioned", Opcode: 2, Since: 3, Args: []argSpec{{Name: "token", Type: argUint}}},
		},
	},
	"xdg_positioner": {
		Name:    "xdg_positioner",
		Version: 7,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "set_size", Opcode: 1, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "set_anchor_rect", Opcode: 2, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "set_anchor", Opcode: 3, Since: 1, Args: []argSpec{{Name: "anchor", Type: argUint}}},
			{Name: "set_gravity", Opcode: 4, Since: 1, Args: []argSpec{{Name: "gravity", Type: argUint}}},
			{Name: "set_constraint_adjustment", Opcode: 5, Since: 1, Args: []argSpec{{Name: "constraint_adjustment", Type: argUint}}},
			{Name: "set_offset", Opcode: 6, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}}},
			{Name: "set_reactive", Opcode: 7, Since: 3},
			{Name: "set_parent_size", Opcode: 8, Since: 3, Args: []argSpec{{Name: "parent_width", Type: argInt}, {Name: "parent_height", Type: argInt}}},
			{Name: "set_parent_configure", Opcode: 9, Since: 3, Args: []argSpec{{Name: "serial", Type: argUint}}},
		},
	},
	"xdg_surface": {
		Name:    "xdg_surface",
		Version: 7,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "get_toplevel", Opcode: 1, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "xdg_toplevel"}}},
			{Name: "get_popup", Opcode: 2, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "xdg_popup"}, {Name: "parent", Type: argObject, Interface: "xdg_surface", Nullable: true}, {Name: "positioner", Type: argObject, Interface: "xdg_positioner"}}},
			{Name: "set_window_geometry", Opcode: 3, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "ack_configure", Opcode: 4, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}}},
		},
		Events: []msgSpec{
			{Name: "configure", Opcode: 0, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}}},
		},
	},
	"xdg_toplevel": {
		Name:    "xdg_toplevel",
		Version: 7,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "set_parent", Opcode: 1, Since: 1, Args: []argSpec{{Name: "parent", Type: argObject, Interface: "xdg_toplevel", Nullable: true}}},
			{Name: "set_title", Opcode: 2, Since: 1, Args: []argSpec{{Name: "title", Type: argString}}},
			{Name: "set_app_id", Opcode: 3, Since: 1, Args: []argSpec{{Name: "app_id", Type: argString}}},
			{Name: "show_window_menu", Opcode: 4, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}, {Name: "serial", Type: argUint}, {Name: "x", Type: argInt}, {Name: "y", Type: argInt}}},
			{Name: "move", Opcode: 5, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}, {Name: "serial", Type: argUint}}},
			{Name: "resize", Opcode: 6, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}, {Name: "serial", Type: argUint}, {Name: "edges", Type: argUint}}},
			{Name: "set_max_size", Opcode: 7, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "set_min_size", Opcode: 8, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "set_maximized", Opcode: 9, Since: 1},
			{Name: "unset_maximized", Opcode: 10, Since: 1},
			{Name: "set_fullscreen", Opcode: 11, Since: 1, Args: []argSpec{{Name: "output", Type: argObject, Interface: "wl_output", Nullable: true}}},
			{Name: "unset_fullscreen", Opcode: 12, Since: 1},
			{Name: "set_minimized", Opcode: 13, Since: 1},
		},
		Events: []msgSpec{
			{Name: "configure", Opcode: 0, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}, {Name: "states", Type: argArray}}},
			{Name: "close", Opcode: 1, Since: 1},
			{Name: "configure_bounds", Opcode: 2, Since: 4, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "wm_capabilities", Opcode: 3, Since: 5, Args: []argSpec{{Name: "capabilities", Type: argArray}}},
		},
	},
	"xdg_wm_base": {
		Name:    "xdg_wm_base",
		Version: 7,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "create_positioner", Opcode: 1, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "xdg_positioner"}}},
			{Name: "get_xdg_surface", Opcode: 2, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "xdg_surface"}, {Name: "surface", Type: argObject, Interface: "wl_surface"}}},
			{Name: "pong", Opcode: 3, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}}},
		},
		Events: []msgSpec{
			{Name: "ping", Opcode: 0, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}}},
		},
	},
	"zwlr_foreign_toplevel_handle_v1": {
		Name:    "zwlr_foreign_toplevel_handle_v1",
		Version: 3,
		Requests: []msgSpec{
			{Name: "set_maximized", Opcode: 0, Since: 1},
			{Name: "unset_maximized", Opcode: 1, Since: 1},
			{Name: "set_minimized", Opcode: 2, Since: 1},
			{Name: "unset_minimized", Opcode: 3, Since: 1},
			{Name: "activate", Opcode: 4, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}}},
			{Name: "close", Opcode: 5, Since: 1},
			{Name: "set_rectangle", Opcode: 6, Since: 1, Args: []argSpec{{Name: "surface", Type: argObject, Interface: "wl_surface"}, {Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "destroy", Opcode: 7, Since: 1, Destructor: true},
			{Name: "set_fullscreen", Opcode: 8, Since: 2, Args: []argSpec{{Name: "output", Type: argObject, Interface: "wl_output", Nullable: true}}},
			{Name: "unset_fullscreen", Opcode: 9, Since: 2},
		},
		Events: []msgSpec{
			{Name: "title", Opcode: 0, Since: 1, Args: []argSpec{{Name: "title", Type: argString}}},
			{Name: "app_id", Opcode: 1, Since: 1, Args: []argSpec{{Name: "app_id", Type: argString}}},
			{Name: "output_enter", Opcode: 2, Since: 1, Args: []argSpec{{Name: "output", Type: argObject, Interface: "wl_output"}}},
			{Name: "output_leave", Opcode: 3, Since: 1, Args: []argSpec{{Name: "output", Type: argObject, Interface: "wl_output"}}},
			{Name: "state", Opcode: 4, Since: 1, Args: []argSpec{{Name: "state", Type: argArray}}},
			{Name: "done", Opcode: 5, Since: 1},
			{Name: "closed", Opcode: 6, Since: 1},
			{Name: "parent", Opcode: 7, Since: 3, Args: []argSpec{{Name: "parent", Type: argObject, Interface: "zwlr_foreign_toplevel_handle_v1", Nullable: true}}},
		},
	},
	"zwlr_foreign_toplevel_manager_v1": {
		Name:    "zwlr_foreign_toplevel_manager_v1",
		Version: 3,
		Requests: []msgSpec{
			{Name: "stop", Opcode: 0, Since: 1},
		},
		Events: []msgSpec{
			{Name: "toplevel", Opcode: 0, Since: 1, Args: []argSpec{{Name: "toplevel", Type: argNewID, Interface: "zwlr_foreign_toplevel_handle_v1"}}},
			{Name: "finished", Opcode: 1, Since: 1},
		},
	},
	"zwlr_output_configuration_head_v1": {
		Name:    "zwlr_output_configuration_head_v1",
		Version: 4,
		Requests: []msgSpec{
			{Name: "set_mode", Opcode: 0, Since: 1, Args: []argSpec{{Name: "mode", Type: argObject, Interface: "zwlr_output_mode_v1"}}},
			{Name: "set_custom_mode", Opcode: 1, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}, {Name: "refresh", Type: argInt}}},
			{Name: "set_position", Opcode: 2, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}}},
			{Name: "set_transform", Opcode: 3, Since: 1, Args: []argSpec{{Name: "transform", Type: argInt}}},
			{Name: "set_scale", Opcode: 4, Since: 1, Args: []argSpec{{Name: "scale", Type: argFixed}}},
			{Name: "set_adaptive_sync", Opcode: 5, Since: 4, Args: []argSpec{{Name: "state", Type: argUint}}},
		},
	},
	"zwlr_output_configuration_v1": {
		Name:    "zwlr_output_configuration_v1",
		Version: 4,
		Requests: []msgSpec{
			{Name: "enable_head", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "zwlr_output_configuration_head_v1"}, {Name: "head", Type: argObject, Interface: "zwlr_output_head_v1"}}},
			{Name: "disable_head", Opcode: 1, Since: 1, Args: []argSpec{{Name: "head", Type: argObject, Interface: "zwlr_output_head_v1"}}},
			{Name: "apply", Opcode: 2, Since: 1},
			{Name: "test", Opcode: 3, Since: 1},
			{Name: "destroy", Opcode: 4, Since: 1, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "succeeded", Opcode: 0, Since: 1},
			{Name: "failed", Opcode: 1, Since: 1},
			{Name: "cancelled", Opcode: 2, Since: 1},
		},
	},
	"zwlr_output_head_v1": {
		Name:    "zwlr_output_head_v1",
		Version: 4,
		Requests: []msgSpec{
			{Name: "release", Opcode: 0, Since: 3, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "name", Opcode: 0, Since: 1, Args: []argSpec{{Name: "name", Type: argString}}},
			{Name: "description", Opcode: 1, Since: 1, Args: []argSpec{{Name: "description", Type: argString}}},
			{Name: "physical_size", Opcode: 2, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "mode", Opcode: 3, Since: 1, Args: []argSpec{{Name: "mode", Type: argNewID, Interface: "zwlr_output_mode_v1"}}},
			{Name: "enabled", Opcode: 4, Since: 1, Args: []argSpec{{Name: "enabled", Type: argInt}}},
			{Name: "current_mode", Opcode: 5, Since: 1, Args: []argSpec{{Name: "mode", Type: argObject, Interface: "zwlr_output_mode_v1"}}},
			{Name: "position", Opcode: 6, Since: 1, Args: []argSpec{{Name: "x", Type: argInt}, {Name: "y", Type: argInt}}},
			{Name: "transform", Opcode: 7, Since: 1, Args: []argSpec{{Name: "transform", Type: argInt}}},
			{Name: "scale", Opcode: 8, Since: 1, Args: []argSpec{{Name: "scale", Type: argFixed}}},
			{Name: "finished", Opcode: 9, Since: 1},
			{Name: "make", Opcode: 10, Since: 2, Args: []argSpec{{Name: "make", Type: argString}}},
			{Name: "model", Opcode: 11, Since: 2, Args: []argSpec{{Name: "model", Type: argString}}},
			{Name: "serial_number", Opcode: 12, Since: 2, Args: []argSpec{{Name: "serial_number", Type: argString}}},
			{Name: "adaptive_sync", Opcode: 13, Since: 4, Args: []argSpec{{Name: "state", Type: argUint}}},
		},
	},
	"zwlr_output_manager_v1": {
		Name:    "zwlr_output_manager_v1",
		Version: 4,
		Requests: []msgSpec{
			{Name: "create_configuration", Opcode: 0, Since: 1, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "zwlr_output_configuration_v1"}, {Name: "serial", Type: argUint}}},
			{Name: "stop", Opcode: 1, Since: 1},
		},
		Events: []msgSpec{
			{Name: "head", Opcode: 0, Since: 1, Args: []argSpec{{Name: "head", Type: argNewID, Interface: "zwlr_output_head_v1"}}},
			{Name: "done", Opcode: 1, Since: 1, Args: []argSpec{{Name: "serial", Type: argUint}}},
			{Name: "finished", Opcode: 2, Since: 1, Destructor: true},
		},
	},
	"zwlr_output_mode_v1": {
		Name:    "zwlr_output_mode_v1",
		Version: 3,
		Requests: []msgSpec{
			{Name: "release", Opcode: 0, Since: 3, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "size", Opcode: 0, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "refresh", Opcode: 1, Since: 1, Args: []argSpec{{Name: "refresh", Type: argInt}}},
			{Name: "preferred", Opcode: 2, Since: 1},
			{Name: "finished", Opcode: 3, Since: 1},
		},
	},
	"zwlr_screencopy_frame_v1": {
		Name:    "zwlr_screencopy_frame_v1",
		Version: 3,
		Requests: []msgSpec{
			{Name: "copy", Opcode: 0, Since: 1, Args: []argSpec{{Name: "buffer", Type: argObject, Interface: "wl_buffer"}}},
			{Name: "destroy", Opcode: 1, Since: 1, Destructor: true},
			{Name: "copy_with_damage", Opcode: 2, Since: 2, Args: []argSpec{{Name: "buffer", Type: argObject, Interface: "wl_buffer"}}},
		},
		Events: []msgSpec{
			{Name: "buffer", Opcode: 0, Since: 1, Args: []argSpec{{Name: "format", Type: argUint}, {Name: "width", Type: argUint}, {Name: "height", Type: argUint}, {Name: "stride", Type: argUint}}},
			{Name: "flags", Opcode: 1, Since: 1, Args: []argSpec{{Name: "flags", Type: argUint}}},
			{Name: "ready", Opcode: 2, Since: 1, Args: []argSpec{{Name: "tv_sec_hi", Type: argUint}, {Name: "tv_sec_lo", Type: argUint}, {Name: "tv_nsec", Type: argUint}}},
			{Name: "failed", Opcode: 3, Since: 1},
			{Name: "damage", Opcode: 4, Since: 2, Args: []argSpec{{Name: "x", Type: argUint}, {Name: "y", Type: argUint}, {Name: "width", Type: argUint}, {Name: "height", Type: argUint}}},
			{Name: "linux_dmabuf", Opcode: 5, Since: 3, Args: []argSpec{{Name: "format", Type: argUint}, {Name: "width", Type: argUint}, {Name: "height", Type: argUint}}},
			{Name: "buffer_done", Opcode: 6, Since: 3},
		},
	},
	"zwlr_screencopy_manager_v1": {
		Name:    "zwlr_screencopy_manager_v1",
		Version: 3,
		Requests: []msgSpec{
			{Name: "capture_output", Opcode: 0, Since: 1, Args: []argSpec{{Name: "frame", Type: argNewID, Interface: "zwlr_screencopy_frame_v1"}, {Name: "overlay_cursor", Type: argInt}, {Name: "output", Type: argObject, Interface: "wl_output"}}},
			{Name: "capture_output_region", Opcode: 1, Since: 1, Args: []argSpec{{Name: "frame", Type: argNewID, Interface: "zwlr_screencopy_frame_v1"}, {Name: "overlay_cursor", Type: argInt}, {Name: "output", Type: argObject, Interface: "wl_output"}, {Name: "x", Type: argInt}, {Name: "y", Type: argInt}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}}},
			{Name: "destroy", Opcode: 2, Since: 1, Destructor: true},
		},
	},
	"zwlr_virtual_pointer_manager_v1": {
		Name:    "zwlr_virtual_pointer_manager_v1",
		Version: 2,
		Requests: []msgSpec{
			{Name: "create_virtual_pointer", Opcode: 0, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat", Nullable: true}, {Name: "id", Type: argNewID, Interface: "zwlr_virtual_pointer_v1"}}},
			{Name: "destroy", Opcode: 1, Since: 1, Destructor: true},
			{Name: "create_virtual_pointer_with_output", Opcode: 2, Since: 2, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat", Nullable: true}, {Name: "output", Type: argObject, Interface: "wl_output", Nullable: true}, {Name: "id", Type: argNewID, Interface: "zwlr_virtual_pointer_v1"}}},
		},
	},
	"zwlr_virtual_pointer_v1": {
		Name:    "zwlr_virtual_pointer_v1",
		Version: 2,
		Requests: []msgSpec{
			{Name: "motion", Opcode: 0, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "dx", Type: argFixed}, {Name: "dy", Type: argFixed}}},
			{Name: "motion_absolute", Opcode: 1, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "x", Type: argUint}, {Name: "y", Type: argUint}, {Name: "x_extent", Type: argUint}, {Name: "y_extent", Type: argUint}}},
			{Name: "button", Opcode: 2, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "button", Type: argUint}, {Name: "state", Type: argUint}}},
			{Name: "axis", Opcode: 3, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "axis", Type: argUint}, {Name: "value", Type: argFixed}}},
			{Name: "frame", Opcode: 4, Since: 1},
			{Name: "axis_source", Opcode: 5, Since: 1, Args: []argSpec{{Name: "axis_source", Type: argUint}}},
			{Name: "axis_stop", Opcode: 6, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "axis", Type: argUint}}},
			{Name: "axis_discrete", Opcode: 7, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "axis", Type: argUint}, {Name: "value", Type: argFixed}, {Name: "discrete", Type: argInt}}},
			{Name: "destroy", Opcode: 8, Since: 1, Destructor: true},
		},
	},
	"zwp_linux_buffer_params_v1": {
		Name:    "zwp_linux_buffer_params_v1",
		Version: 6,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "add", Opcode: 1, Since: 1, Args: []argSpec{{Name: "fd", Type: argFD}, {Name: "plane_idx", Type: argUint}, {Name: "offset", Type: argUint}, {Name: "stride", Type: argUint}, {Name: "modifier_hi", Type: argUint}, {Name: "modifier_lo", Type: argUint}}},
			{Name: "create", Opcode: 2, Since: 1, Args: []argSpec{{Name: "width", Type: argInt}, {Name: "height", Type: argInt}, {Name: "format", Type: argUint}, {Name: "flags", Type: argUint}}},
			{Name: "create_immed", Opcode: 3, Since: 2, Args: []argSpec{{Name: "buffer_id", Type: argNewID, Interface: "wl_buffer"}, {Name: "width", Type: argInt}, {Name: "height", Type: argInt}, {Name: "format", Type: argUint}, {Name: "flags", Type: argUint}}},
			{Name: "set_sampling_device", Opcode: 4, Since: 6, Args: []argSpec{{Name: "device", Type: argArray}}},
		},
		Events: []msgSpec{
			{Name: "created", Opcode: 0, Since: 1, Args: []argSpec{{Name: "buffer", Type: argNewID, Interface: "wl_buffer"}}},
			{Name: "failed", Opcode: 1, Since: 1},
		},
	},
	"zwp_linux_dmabuf_feedback_v1": {
		Name:    "zwp_linux_dmabuf_feedback_v1",
		Version: 6,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
		},
		Events: []msgSpec{
			{Name: "done", Opcode: 0, Since: 1},
			{Name: "format_table", Opcode: 1, Since: 1, Args: []argSpec{{Name: "fd", Type: argFD}, {Name: "size", Type: argUint}}},
			{Name: "main_device", Opcode: 2, Since: 1, Args: []argSpec{{Name: "device", Type: argArray}}},
			{Name: "tranche_done", Opcode: 3, Since: 1},
			{Name: "tranche_target_device", Opcode: 4, Since: 1, Args: []argSpec{{Name: "device", Type: argArray}}},
			{Name: "tranche_formats", Opcode: 5, Since: 1, Args: []argSpec{{Name: "indices", Type: argArray}}},
			{Name: "tranche_flags", Opcode: 6, Since: 1, Args: []argSpec{{Name: "flags", Type: argUint}}},
		},
	},
	"zwp_linux_dmabuf_v1": {
		Name:    "zwp_linux_dmabuf_v1",
		Version: 6,
		Requests: []msgSpec{
			{Name: "destroy", Opcode: 0, Since: 1, Destructor: true},
			{Name: "create_params", Opcode: 1, Since: 1, Args: []argSpec{{Name: "params_id", Type: argNewID, Interface: "zwp_linux_buffer_params_v1"}}},
			{Name: "get_default_feedback", Opcode: 2, Since: 4, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "zwp_linux_dmabuf_feedback_v1"}}},
			{Name: "get_surface_feedback", Opcode: 3, Since: 4, Args: []argSpec{{Name: "id", Type: argNewID, Interface: "zwp_linux_dmabuf_feedback_v1"}, {Name: "surface", Type: argObject, Interface: "wl_surface"}}},
		},
		Events: []msgSpec{
			{Name: "format", Opcode: 0, Since: 1, Args: []argSpec{{Name: "format", Type: argUint}}},
			{Name: "modifier", Opcode: 1, Since: 3, Args: []argSpec{{Name: "format", Type: argUint}, {Name: "modifier_hi", Type: argUint}, {Name: "modifier_lo", Type: argUint}}},
		},
	},
	"zwp_virtual_keyboard_manager_v1": {
		Name:    "zwp_virtual_keyboard_manager_v1",
		Version: 1,
		Requests: []msgSpec{
			{Name: "create_virtual_keyboard", Opcode: 0, Since: 1, Args: []argSpec{{Name: "seat", Type: argObject, Interface: "wl_seat"}, {Name: "id", Type: argNewID, Interface: "zwp_virtual_keyboard_v1"}}},
		},
	},
	"zwp_virtual_keyboard_v1": {
		Name:    "zwp_virtual_keyboard_v1",
		Version: 1,
		Requests: []msgSpec{
			{Name: "keymap", Opcode: 0, Since: 1, Args: []argSpec{{Name: "format", Type: argUint}, {Name: "fd", Type: argFD}, {Name: "size", Type: argUint}}},
			{Name: "key", Opcode: 1, Since: 1, Args: []argSpec{{Name: "time", Type: argUint}, {Name: "key", Type: argUint}, {Name: "state", Type: argUint}}},
			{Name: "modifiers", Opcode: 2, Since: 1, Args: []argSpec{{Name: "mods_depressed", Type: argUint}, {Name: "mods_latched", Type: argUint}, {Name: "mods_locked", Type: argUint}, {Name: "group", Type: argUint}}},
			{Name: "destroy", Opcode: 3, Since: 1, Destructor: true},
		},
	},
}
